      - job_name: 'istio-prometheus'
        scrape_interval: 15s
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - istio-system
        relabel_configs:
        - source_labels: [__name__]
          action: replace
          target_label: __name__
        params:
          'match[]'
          - '{__name__=~"workload:(.*)"}'
          - '{__name__=~"pilot(.*)"}'